# Register user
POST {{baseurl}}/auth/register
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
# Login
POST {{baseurl}}/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "password": "{{password}}"
}

###
# Get features
GET {{baseurl}}/features
Authorization: Bearer {{accessToken}}

###
# Get envitronments
GET {{baseurl}}/environments
Authorization: Bearer {{accessToken}}

###
# Add feature
POST {{baseurl}}/feature
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{featurename}}",
    "description": "Test feature description" 
}

###
# Add environment
POST {{baseurl}}/environment
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "name": "{{environmentName}}" 
}

###
# Add environment to feature (update with valid ids)
POST {{baseurl}}/feature/environment
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "featureId": "b433ac01-77ba-4e43-a532-663ef32ba625",
    "environmentId": "4f16e81e-1924-4b4e-865a-b14813a627c0"
}

###
# Toggle feature in environment (update with valid ids)
PUT {{baseurl}}/feature/toggle
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
    "featureId": "b433ac01-77ba-4e43-a532-663ef32ba625",
    "environmentId": "4f16e81e-1924-4b4e-865a-b14813a627c0" 
}

###
# Get feature state
GET {{baseurl}}/feature/{{featurename}}/environment/4f16e81e-1924-4b4e-865a-b14813a627c0

###